<div class="row">
    <div class="col-7 mt-5 mx-auto text-center">
        <h4>Server Time - </h4>
        <h2><?php echo $time; ?></h2>
    </div>
</div>

<?php
echo $this->tag->linkTo(["/user/signup", "Add User!", 'class' => 'btn btn-primary']);
echo $this->tag->form(""); ?>


<input type="submit" name='log' value="logout" class="btn btn-danger float-right " />
</form>
<?php
if ($users)
    if ($users->count() > 0) {
?>

    <table class="table table-bordered table-hover">
        <thead class="thead-light">
            <tr>
                <th>User_ID</th>
                <th>Name</th>
                <th>Email</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="3">Users quantity: <?php echo $users->count(); ?></td>
            </tr>
        </tfoot>
        <tbody>
            <?php


            foreach ($users as $user) { ?>
                <tr>
                    <td><?php echo $user->user_id; ?></td>
                    <td><?php echo $user->name; ?></td>
                    <td><?php echo $user->email; ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>

<?php
    };
