<h2>Add user</h2>

<?php echo $this->tag->form(""); ?>

<p>
    <label for="name">Name</label>
    <?php echo $this->tag->textField("name"); ?>
</p>

<p>
    <label for="email">E-Mail</label>
    <?php echo $this->tag->textField("email"); ?>
</p>
<p>
    <label for="password">Password</label>
    <?php echo $this->tag->textField("password"); ?>
</p>


<p>
    <?php echo $this->tag->submitButton(["Register", "class" => "btn btn-primary"]);
    echo "<br><h3 class='text-danger'>" . $message . "</h3>";
    ?>
</p>

</form>